### ISSUE TITLE
Tensorflow SAC Model

### ISSUE THREAD

**Issue by harman097** [harman097/RoboRugby#46]
Convert the SAC tutorial to work on RoboRugby. Can haz results?

Link: https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial

**Comment by harman097** [comment]
Currently there's an issue with the "LEARNERS" (probly):

2020-09-06 15:30:01.022609: E tensorflow/core/kernels/check_numerics_op.cc:292] abnormal_detected_host @0x7f3ba1e03d00 = {1, 0} Critic loss is inf or nan.
Traceback (most recent call last):
  File "/home/harman097/Projects/RoboRugby/Training_SAC.py", line 254, in <module>
    loss_info = agent_learner.run(iterations=1)
  File "/home/harman097/.local/lib/python3.8/site-packages/tf_agents/experimental/train/learner.py", line 176, in run
    loss_info = self._train(iterations, iterator)
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/harman097/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
  (0) Invalid argument:  Critic loss is inf or nan. : Tensor had NaN values
	 [[node CheckNumerics (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:309) ]]
	 [[while/LoopCond/_142/_347]]
  (1) Invalid argument:  Critic loss is inf or nan. : Tensor had NaN values
	 [[node CheckNumerics (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:309) ]]
	 [[Func/Losses/actor_loss/write_summary/summary_cond/then/_10/input/_185/_187]]
  (2) Invalid argument:  Critic loss is inf or nan. : Tensor had NaN values
	 [[node CheckNumerics (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:309) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__train_4332818]

Errors may have originated from an input operation.
Input Source operations connected to node CheckNumerics:
 mul (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:299)

Input Source operations connected to node CheckNumerics:
 mul (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:299)

Input Source operations connected to node CheckNumerics:
 mul (defined at /.local/lib/python3.8/site-packages/tf_agents/agents/sac/sac_agent.py:299)

Function call stack:
_train -> _train -> _train


Process finished with exit code 1
